server:
  port: 8585
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/coupon_service_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format-sql: true
      
      
      