server:
  port: 8085
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/coupon_service_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format-sql: true
  application:
    name: coupon-service
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    
    
    
    service-url:
      defaultZone : http://localhost:8761/eureka
      
      
    
      
      
      