spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service_db
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update
    
   database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: product-service
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
    
server:
  port: 8084
    

  
  

     
      


      
      
    
      
      
    